[package]
name = "jabu_debug_draw"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.9", default-features = false, features = [ "render", "bevy_asset" ] }

[dev-dependencies]
bevy = { version = "0.9", default-features = true }
